### ISSUE TITLE
Simplify the relay of ROS mixed ports to SeRoNet ports

### ISSUE THREAD

**Issue by NadiaHG** [seronet-project/SeRoNet-Tooling-ROS-Mixed-Port#14]
I would like to simplify for end-users the integration of Ros components with SeRoNet. Having the M2M for communication objects integrated https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/pull/11 , we could facilitate considerably  to  the user the integration.

The process to **relay** Ros messages to SeRoNet messages is the following, @alex-lotz please correct me if I am wrong:

1. Create a SeRoNet component
2. "Import" the rosinterfacespool file
3. Add a SeRoNet-Ros mixed port
4. Select from the pool the interfaces for the port
5. Create the SeRoNet Port (the user have to decide the service type, the communication object and the direction of the communication)
5. Create the activity 
6. Link the Ros-mixed port to the activity and link the SeRoNet port to the activity
7. Modify consequently the code for the activity to match both messages

My idea is create a plugin that is able to automatically perform the steps 4 to 7. This plugin will be complementary to the current manual approach, probably available as a button.

@alex-lotz is this ok for you?

**Comment by alex-lotz** [comment]
@ipa-nhg I think step number 5. is not correct. In most situations, the seronet services already exist, just like in most cases the related ROS interfaces already exist. So the "port" (or rather the service) is not created manually but it already exists and the overall idea of a mixed port component is to select and to connect related (existing) ports of both sides. Of course we could generate new ROS interfaces from existing SeRoNet services, or generate new SeRoNet services from existing ROS interfaces. But I think this would not really solve the problem of actually connecting existing worlds, because if you generate new ports that nobody uses, it will just "polute" the other side without addressing the actual interconnection problem.

**Comment by NadiaHG** [comment]
@alex-lotz yes, I know we have more use cases, and likely the SeRoNet Port already exists and the user will not create a new one.

I just want to cover the case that you want to relay messages from ROS to SeRoNet. For this case I can **suggest** to the user which port is needed for the other side and the code for the activity. 

This is just a help function and I am not planning to call it by default by creating a new ROS-SeRoNet mixed port. Let's put it this way;  I want to automate this tutorial use case https://wiki.servicerobotik-ulm.de/tutorials:ros:mixed-port-component-ros

**Comment by alex-lotz** [comment]
@ipa-nhg If this is an optional feature that one can manually trigger if wanted, then I think it is ok from my point of view. Just provide a new command to manually trigger the related M2M transformation, then it is fine.

**Comment by NadiaHG** [comment]
Done, merged, tested and documented

https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/tree/master/de.seronet_projekt.ros.componentGateway.generator#automatic-transformation-of-ros-components-to-seronet-mixed-ports

Full process: https://github.com/ipa320/ros-model/blob/master/docu/ROSSeRoNet.md
